name: Tets

on:
  pull_request:
    types: [synchronize, ready_for_review]
    paths:
      - "**"
      - "!/*.md"
      - "!/**.md"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --release --no-fail-fast
      - name: Build
        run: cargo build --release
